language: node_js
node_js:
 - "stable"
script:
 - npm run build
 - npm test
cache:
 directories:
 - node_modules
deploy:
 provider: pages
 skip_cleanup: true
 local_dir: build
 github_token: $github_token
 on:
  branch: main 
notifications:
 slack: is-parcial3:0cll7B5cPzovBcK0cYEuQVt7

  # notifications:
  # slack:
  #   rooms:
  #   - is-parcial3:0cll7B5cPzovBcK0cYEuQVt7#general
  #   - is-parcial3:0cll7B5cPzovBcK0cYEuQVt7#random

  #   token 0cll7B5cPzovBcK0cYEuQVt7

  #   travis encrypt "is-parcial3:0cll7B5cPzovBcK0cYEuQVt7" --add notifications.slack -r accountName/repoName

  #   travis encrypt "is-parcial3:0cll7B5cPzovBcK0cYEuQVt7" --add notifications.slack